### ISSUE TITLE
White Blank screen

### ISSUE THREAD

**Issue by daurenm** [rodrigoreal/ionic2-angularfire-login#1]
I cloned the folder, but it doesn't work (blank screen). 
By adding the this line `/// <reference path="../node_modules/angularfire2/firebase3.d.ts"/>,` i got rid of all 'Cannot find module 'firebase' errors, but then these errors come up in auth.ts: 26th line: 
`TypeScript error: /home/red/Documents/ionic2/workingSample/app/providers/auth/auth.ts(26,49): Error TS2345: Argument of type '(authData: FirebaseAuthData) => void' is not assignable to parameter of type '(a: FirebaseAuthState) => any'.`
`Types of parameters 'authData' and 'a' are incompatible.`
`Type 'FirebaseAuthState' is not assignable to type 'FirebaseAuthData'.`
`Types of property 'provider' are incompatible.`
`Type 'AuthProviders' is not assignable to type 'string'.`

`TypeScript error: /home/red/Documents/ionic2/workingSample/node_modules/angularfire2/providers/auth.d.ts(12,20): Error TS1112: A class member cannot be declared optional.`

`TypeScript error: /home/red/Documents/ionic2/workingSample/node_modules/angularfire2/utils/firebase_object_observable.d.ts(6,17): Error TS1112: A class member cannot be declared optional.`

`TypeScript error: node_modules/angularfire2/firebase3.d.ts(414,3): Error TS2300: Duplicate identifier 'export='.`

`TypeScript error: typings/main/ambient/firebase/index.d.ts(328,2): Error TS2300: Duplicate identifier 'export='.`

Any ideas?

**Comment by rodrigoreal** [comment]
Yeah, that is a problem with the current angularfire version, it will be fixed in the next release but in the mean time you can use `npm install angularfire2@next`
