### ISSUE TITLE
No idToken and accessToken return despite of webClientId fullfiled

### ISSUE THREAD

**Issue by nampdn** [rodrigoreal/ionic2-angularfire-login#13]
I can successfully authenticated with Google Plus, then it only return the `email` and `oauthToken` fields.
I have filled the `webClientId` with my webClientId provided from the Firebase config.
@rodrigoreal Please help me, Thanks in advance!

**Comment by zefrench** [comment]
Tell us what you need exactly.

**Comment by nampdn** [comment]
Hi, I need the `idToken` and `accessToken` return from the `authData` at this [line](https://github.com/rodrigoreal/ionic2-angularfire-login/blob/master/app/providers/auth/auth.ts#L93)

What I got when running in the device are only `email` and `oauthToken` without `idToken` inside it.

Here is my development info:
**Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
OS: Win10
Node Version: v6.3.1**

**Comment by rodrigoreal** [comment]
The google authentication has been removed at this moment, and the project has been updated to rc0 version.
