### ISSUE TITLE
Getting compilation errors.

### ISSUE THREAD

**Issue by adarshdeep-kamboj** [rodrigoreal/ionic2-angularfire-login#14]
on executing ionic serve -l
I am getting below errors:

TypeScript error: /home/adarshdeep/Downloads/ionic2-angularfire-login-master/app/providers/auth/auth.ts(53,9): Error TS2304: Cannot find name 'facebookConnectPlugin'.
TypeScript error: /home/adarshdeep/Downloads/ionic2-angularfire-login-master/app/providers/auth/auth.ts(54,61): Error TS2339: Property 'credential' does not exist on type 'typeof FacebookAuthProvider'.
TypeScript error: /home/adarshdeep/Downloads/ionic2-angularfire-login-master/app/providers/auth/auth.ts(61,7): Error TS2304: Cannot find name 'facebookConnectPlugin'.
TypeScript error: /home/adarshdeep/Downloads/ionic2-angularfire-login-master/app/providers/auth/auth.ts(85,14): Error TS2339: Property 'plugins' does not exist on type 'Window'.
TypeScript error: /home/adarshdeep/Downloads/ionic2-angularfire-login-master/app/providers/auth/auth.ts(93,61): Error TS2339: Property 'credential' does not exist on type 'typeof GoogleAuthProvider'.
TypeScript error: /home/adarshdeep/Downloads/ionic2-angularfire-login-master/app/providers/auth/auth.ts(113,59): Error TS2339: Property 'credential' does not exist on type 'typeof GoogleAuthProvider'.

**Comment by Caff00** [comment]
I have the same errors

**Comment by Vasanth19** [comment]
+1

**Comment by FonMaestro** [comment]
The same here

**Comment by rodrigoreal** [comment]
The project has been updated to rc0 version, and fixed theses errors.
