### ISSUE TITLE
"nonce" variable always "00000"

### ISSUE THREAD

**Issue by ThadeuLuz** [rodrigoreal/ionic2-angularfire-login#15]
Sorry in advance if I missed something, but [this line](https://github.com/rodrigoreal/ionic2-angularfire-login/blob/master/app/providers/auth/auth.ts#L129) always generates "00000".

According to [the docs](https://developers.google.com/identity/protocols/OAuth2UserAgent) it should be "A cryptographically strong random string that you use to prevent intercepted responses from being reused. The Google Authorization Server round-trips this parameter; you must verify your application receives the same value it sent."

**Comment by rodrigoreal** [comment]
Sorry, but the google authentication has been removed at this moment, and the project has been updated to rc0 version.
