### ISSUE TITLE
Facebook configuration

### ISSUE THREAD

**Issue by ricardocunha** [rodrigoreal/ionic2-angularfire-login#17]
Hi, I did facebook steps but I get the following error:

"Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.."

What I need to put for work in my browser or/and my emulator/device?

**Comment by rodrigoreal** [comment]
Hey man, i forgot to put one step on the facebook steps..
You need to put the url you get from firebase when you enable facebook, and put that into the facebook url, in your facebook app.

1- Get the firebase url when you enable facebook
2- Go to your app in the facebook developer
3- Go to configurations/basic
4- Add the url to the app domain tab

If u didn't changed the firebase credentials you will need to use mine for the moment: https://ionic2-angularfire-login-14ea3.firebaseapp.com/__/auth/handler 

But it is very important that you create your credentials for production.

See if that work

**Comment by ricardocunha** [comment]
great, now it's working
