### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by BurcaCiprian** [rodrigoreal/ionic2-angularfire-login#21]
npm install @types/request@0.0.30 --save-dev --save-exact
Password:
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@types/request@0.0.30" "--save-dev" "--save-exact"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9

npm ERR! Unexpected token < in JSON at position 1
npm ERR! 
npm ERR! <?xml version="1.0" encoding="utf-8"?>
npm ERR! <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
npm ERR!  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm ERR! <html>
npm ERR!   <head>
npm ERR!     <title>503 No healthy backends</title>
npm ERR!   </head>
npm ERR!   <body>
npm ERR!     <h1>Error 503 No healthy backends</h1>
npm ERR!     <p>No healthy backends</p>
npm ERR!     <h3>Guru Mediation:</h3>
npm ERR!     <p>Details: cache-lhr6322-LHR 1484232824 3922796935</p>
npm ERR!     <hr>
npm ERR!     <p>Varnish cache server</p>
npm ERR!   </body>
npm ERR! </html>
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

----------

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.2 Build version 8C38

**Comment by rodrigoreal** [comment]
@BurcaCiprian  i've upgraded the project with the latest ionic version
