### ISSUE TITLE
npm install failes

### ISSUE THREAD

**Issue by naderafshari** [rodrigoreal/ionic2-angularfire-login#22]
$ npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @angular/common@2.2.1 requires a peer of @angular/core@2.2.1 but none was installed.
npm WARN @angular/compiler-cli@2.2.1 requires a peer of @angular/compiler@2.2.1 but none was installed.
npm WARN @angular/compiler-cli@2.2.1 requires a peer of @angular/core@2.2.1 but none was installed.
npm WARN @angular/forms@2.2.1 requires a peer of @angular/core@2.2.1 but none was installed.
npm WARN @angular/http@2.2.1 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN @angular/http@2.2.1 requires a peer of @angular/core@2.2.1 but none was installed.
npm WARN @angular/platform-browser@2.2.1 requires a peer of @angular/core@2.2.1 but none was installed.
npm WARN @angular/platform-browser-dynamic@2.2.1 requires a peer of @angular/core@2.2.1 but none was installed.
npm WARN @angular/platform-browser-dynamic@2.2.1 requires a peer of @angular/compiler@2.2.1 but none was installed.
npm WARN @angular/platform-server@2.2.1 requires a peer of @angular/core@2.2.1 but none was installed.
npm WARN @angular/platform-server@2.2.1 requires a peer of @angular/compiler@2.2.1 but none was installed.
npm WARN ionic-angular@2.0.1 requires a peer of @angular/compiler@2.2.1 but none was installed.
npm WARN ionic-angular@2.0.1 requires a peer of @angular/core@2.2.1 but none was installed.
npm WARN ionic-angular@2.0.1 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN ionic-angular@2.0.1 requires a peer of zone.js@~0.6.26 but none was installed.

Also
$ ionic serve
...
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ watch: `ionic-app-scripts watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@ watch script 'ionic-app-scripts watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

latest node and npm installed on the machine

Sorry buy I'm new to all thins and thank you in advance for your help

**Comment by naderafshari** [comment]
the ionic cli generated project don't have any problems

**Comment by rodrigoreal** [comment]
@naderafshari i've upgraded the project with the latest ionic version
