### ISSUE TITLE
the url of image  is  ‘../../assets/img/splash1.jpg’。but  after  packing，the app can not show the  image。

### ISSUE THREAD

**Issue by wangxuyang518** [rodrigoreal/ionic2-angularfire-login#23]
the url of image  is  ‘../../assets/img/splash1.jpg’。but  after  packing，the app can not show the  image。please  help  me

**Comment by rodrigoreal** [comment]
@wxy520ll i've upgraded the project with the latest ionic version, can you check if it is still happening?
