### ISSUE TITLE
Ionic DeepLinkConfig question

### ISSUE THREAD

**Issue by 5im0n** [rodrigoreal/ionic2-angularfire-login#25]
Hey @rodrigoreal,

I'm quite stuck with the deepLinkConfig scenario.
If we use this application as a PWA, it will be great to not redirect the user with `this.nav.setRoot` on the `app.component`.

Some auth pages need to have access to the user auth, but they are loaded before firebase get the auth state of the user. I've try the `ionViewCanEnter` method without success.

Do you have face to the DeepLinkConfig with auth scenario ?

Thank you

**Comment by rodrigoreal** [comment]
Hey @5im0n, i've never used deep link with auth before, so i can't help you much with that.
