### ISSUE TITLE
Cancel subscriptions on logout

### ISSUE THREAD

**Issue by pgegenfurtner** [rodrigoreal/ionic2-angularfire-login#26]
When I use the logout() function you created in the auth-provider, I get a permission_denied exception, because there is still an open subscription to firebase.

I read the issue https://github.com/rodrigoreal/ionic2-angularfire-login/issues/6 but the solution provided there (for an older Version), does not solve the actual problem. 

I'm completely new to ionic and angular, so I don't really know how to unsubscribe.

Could you update the logout function so all open subscriptions are unsubscribed? 

Thanks!

**Comment by rodrigoreal** [comment]
It has been fixed.
