### ISSUE TITLE
Where is the FirebaseAuthData class?

### ISSUE THREAD

**Issue by sathishvj** [rodrigoreal/ionic2-angularfire-login#3]
I tried parts of the code but typescript is failing at the class FirebaseAuthData.  Where is it imported from?

I have already imported FIREBASE_PROVIDERS in app.ts.

fyi, my ionic info is:

```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.8.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: Not installed
ios-sim version: 3.0.0
OS: Mac OS X El Capitan
Node Version: v5.6.0
Xcode version: Xcode 7.3.1 Build version 7D1014
```

Also further down in the code you have:

```
}).catch((error) => {
        if (error) {
          switch (error.code) {
            case "INVALID_EMAIL":
```

What is the type of this error?  How did it get a 'code' field?  Typescript fails to compile this also.

**Comment by rodrigoreal** [comment]
I just fix both errors, they removed the FirebaseAuthData class in the newest angularfire version and i didn't noticed.
I'm still getting 2 errors, but they are an angularfire typing errors, and they will probably fix that.

```
TypeScript error: /Users/rodrigoreal/Projetos/ionic2-angularfire-login/node_modules/angularfire2/providers/auth.d.ts(12,20): Error TS1112: A class member cannot be declared optional.
TypeScript error: /Users/rodrigoreal/Projetos/ionic2-angularfire-login/node_modules/angularfire2/utils/firebase_object_observable.d.ts(6,17): Error TS1112: A class member cannot be declared optional.
```
