### ISSUE TITLE
Facebook Auth error while running the app on android or ios device/simulator

### ISSUE THREAD

**Issue by harpreet2602** [rodrigoreal/ionic2-angularfire-login#4]
Error: This operation is not supported in the environment this application is running on.
"location.protocol" must be http or https.

**Comment by harpreet2602** [comment]
update to angularfire2@2.0.0-beta.3-0930330, blank page issue will go away....Then try the app on a physical device or ios simulation.... you will see the above error.....Easy to recreate....

**Comment by rodrigoreal** [comment]
@harpreet2602 when i created the project the fb login was working, but i went to look if there is a issue about that in the angularfire, and they changed the way to login with fb.

But in the meanwhile you can try the follow steps:
https://github.com/angular/angularfire2/blob/master/docs/5-user-authentication.md#cordova-case

Install cordova pluggin
`cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="123456789" --variable APP_NAME="myApplication"`

Change the fb method in the auth provider

``` ts
loginWithFacebook() {
    return Observable.create(observer => {
      let provider = firebase.auth.FacebookAuthProvider.credential(result.authResponse.accessToken);

      firebase.auth().signInWithCredential(provider).then((success) => {
        observer.next(success);
        console.log("Firebase success: " + JSON.stringify(success));
      })
      .catch((error) => {
        observer.error(error);
        console.log("Firebase failure: " + JSON.stringify(error));
      });
    });
  }
```

I had no time to do that in my project, so i dont know if it will work.
ill update the project as soon as i can.

**Comment by harpreet2602** [comment]
@rodrigoreal , I will try to use the above plugin for fb auth.. I would really recommend you to update the same in your git repo as the crowd is moving towards ionic 2 and angularfire2, FB and google auth is the core of your project it should work flawless...

**Comment by harpreet2602** [comment]
@rodrigoreal, The above way does not worked... Its keeps on complaining about .'credential' method of FacebookAuthProvider

**Comment by MauricioKruijer** [comment]
Maybe it would be possible to use cordova inappbrowser like the [OpenFB](https://github.com/ccoenraets/OpenFB) project. 

This is you you need to you `FacebookAuthProvider.credential()` from the Firebase docs [(Advanced: Handle the sign-in flow manually)](https://firebase.google.com/docs/auth/web/facebook-login)

``` JS
// User is signed-in Facebook.
    var unsubscribe = firebase.auth().onAuthStateChanged(function(firebaseUser) {
      unsubscribe();
      // Check if we are already signed-in Firebase with the correct user.
      if (!isUserEqual(event.authResponse, firebaseUser)) {
        // Build Firebase credential with the Facebook auth token.
        var credential = firebase.auth.FacebookAuthProvider.credential(
            event.authResponse.accessToken);
        // Sign in with the credential from the Facebook user.
        firebase.auth().signInWithCredential(credential).catch(function(error) {
          // Handle Errors here.
          var errorCode = error.code;
          var errorMessage = error.message;
          // The email of the user's account used.
          var email = error.email;
          // The firebase.auth.AuthCredential type that was used.
          var credential = error.credential;
          // ...
        });
      } else {
        // User is already signed-in Firebase with the correct user.
      }
    });
```

**Comment by harpreet2602** [comment]
This does not work with ionic 2...

**Comment by rodrigoreal** [comment]
@harpreet2602 @MauricioKruijer i updated the project and now it is working (i only tested on android, but it should work on iOS also).
If you cloned the repository you will need to do a `npm install`
If you integrated this project inside your own project follow these [steps](https://github.com/rodrigoreal/ionic2-angularfire-login/blob/master/docs/facebook-authentication.md).

I'm using the fb native plugin to get an acess token and send it to firebase, you will get 3 typescripts errors but it is working.

**Comment by harpreet2602** [comment]
@rodrigoreal, I tried on android... The code works but with an issue... It launches the facebook popup but does not show the username and password field... It throws the Error "Given URL is not allowed by application configuration: one or more of the given urls is not allowed by the app's settings. To use this url you must add a valid native platform in your App's setting".... 

I have the cordova-plugin-facebook4 plugin already installed and configured.

**Comment by harpreet2602** [comment]
@rodrigoreal, I reconfigured my fb settings but now I am getting invalid key hash error

**Comment by rodrigoreal** [comment]
@harpreet2602 did you put the "=" at the end of the hash?
Example: `JKQnP+eirtSWFpqkIcN3vScxjEE=`

**Comment by harpreet2602** [comment]
Yes I put "=" ..... There's a bit trick to generate keystore on macosx....Can you please list down the below steps in the installation guide....
1. First create a RSA keystore... "**keytool -genkey -v -keystore ~/.android/debug.keystore -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000**"
2. Then create a keyhash for facebook.... same command that you listed in the installation guide.... "**keytool -exportcert -alias androiddebugkey -keystore ~/.android/debug.keystore | openssl sha1 -binary | openssl base64**"
3. Add the keyhash on facebook under your app dashboard.
4. Sign the android app with the same keystore…
   "**jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ~/.android/debug.keystore platforms/android/build/outputs/apk/android-release-unsigned.apk  androiddebugkey**"
5. Zip align android apk:
   "**~/Library/Android/sdk/build-tools/24.0.1/zipalign -v 4 platforms/android/build/outputs/apk/android-release-unsigned.apk platforms/android/build/outputs/apk/myapp.apk**"

The above info will be helpful as this is the end-end-steps....

FYI.... I am able to run the app on both android and ios.....

@rodrigoreal , you might want to update your git repo with the correct code for google sign-in  aswell, as it gives the same "location.protocol" error...

And, yes, you may close this issue :)

**Comment by ciekawy** [comment]
@harpreet2602 as for the google I've created issue #7 and a corresponding PR https://github.com/rodrigoreal/ionic2-angularfire-login/pull/8

**Comment by rodrigoreal** [comment]
@harpreet2602 thanks for the steps info, i'll update the guide.
@ciekawy thanks for the google contribution.

**Comment by sathishvj** [comment]
So I'm getting the _"location.protocol" must be http or https_ error.  I'm using the email login.  I don't see any code update that does email login and works around this error.  Has that been resolved yet by anybody?

**Comment by sathishvj** [comment]
Has this issue actually been resolved for you all?  I'm still seeing this issue.

Also, I was looking specifically for email login, which doesn't seem to be updated in the current auth.ts.  I'm able to do a login via direct 'firebase.auth()` from the browser, but it still fails at getUserData().

**Comment by ciekawy** [comment]
This issue concerns the user story of ability to Authenticate using Facebook as a provider regardless the particular implementation. 

Since for now the Firebase SDK authentication method is broken due to the issue inside the Firebase SDK, the solution is to switch to another way of integration with Facebook as an authentication provider which is given by the https://github.com/rodrigoreal/ionic2-angularfire-login/commit/de74f4f7f6582cec30ae856539ccce3bb3289e0e (and also requires to do appropriate configuration described in https://github.com/rodrigoreal/ionic2-angularfire-login/blob/master/docs/facebook-authentication.md)

**Comment by richardmarais** [comment]
Hi All,

I have been using `AngularFire2^2.0.0-beta.7.1-pre` (https://github.com/angular/angularfire2/), and also am getting the following error from Firebase:

> This operation is not supported in the environment this application is running on. "location.protocol" must be http or https and web storage must be enabled.

I would like to avoid having to make any changes (or minimal changes) to my code if possible because I have some complex logic around sign in.

**Question** 

If I use this library (`rodrigoreal/ionic2-angularfire-login`) instead of `AngularFire2^2.0.0-beta.7.1-pre`, will I need to make any changes? Or are the interfaces identical?

Thanks

**Comment by rodrigoreal** [comment]
@richardmarais this project is not exactly a library, its an example of how to integrate `angularfire2` with `ionic2`.
So, if you use this project you are still `angularfire2`.
But you can take a look at the [auth provider](https://github.com/rodrigoreal/ionic2-angularfire-login/blob/master/src/providers/auth.ts) and see the `loginWithFacebook`method.
I'm using the native facebook login if it is on mobile, or if it is on the web the web login.

**Comment by richardmarais** [comment]
If I have already coded with AngularFire2 for Google, Facebook and Email login. Email verification, etc. And it all works in a browser, what's my best approach if I am to get it to work on a devise too?

**Comment by richardmarais** [comment]
When you use this project on a device, do you still get the location.protocol error?

**Comment by rodrigoreal** [comment]
@richardmarais i dont think you have any other approach than a `if else`.
```
if (platform.is('cordova')) {
  // use facebook/google native popup
} else {
  // use firebase web popup
}
```

And for your last question, no i'm not.

**Comment by richardmarais** [comment]
@rodrigoreal thanks, appreciate the advise.

With regards to AngularFire2. What's the point of it having api to authenticate with Firebase if it won't work?
