### ISSUE TITLE
Catching exception after logout

### ISSUE THREAD

**Issue by sathishvj** [rodrigoreal/ionic2-angularfire-login#6]
I don't know if others are seeing this error.  When you do a 'logout/signout', are you seeing an exception?  After that the ionic app just hangs for me.  I had to add a function to catch the error from the inner subscribe to handle it.  

```
  getUserData() {
    return Observable.create(observer => {
      this.af.auth.subscribe(
        (authData) => {
          if (authData) {
            this.af.database.object("/users/" + authData.uid).subscribe(
              (userData) => {
                console.log(userData);
                observer.next(userData);
              },
              (ex) => { // added to capture exception after login
                console.log('getUserData(): Found exception: ', ex);
                observer.error(ex);
              }
            );
          } else { 
            console.log('getUserData(): authData was nil: '); // this never seems to be called.
            observer.error();
          }
        },

        (err) => {
          console.log('getUserData(): Error: ', err);
        }
      );
    });
  }
```

Also, why should this be called each time?  It's because of the this.auth.getUserData() in app.ts:initializeApp().  We would ideally need it only the first time right?  How do we cancel that subscription after the first time?  I tried take(1) but that doesn't seem to work.  

```
      this.auth.getUserData().take(1).subscribe(data => { // the take(1) doesn't work
        console.log('Firebase responded with success.');
        this.rootPage = TabsPage;
      }, err => {
        console.log('Firebase responded with error.', err);
        this.rootPage = LoginEmailPage;
      });
```

**Comment by rodrigoreal** [comment]
@sathishvj ill update the method to fix that exception as u said.

And for your question:

> Also, why should this be called each time? It's because of the this.auth.getUserData() in app.ts:initializeApp(). We would ideally need it only the first time right?

I'm using a subscription because 2 things:
1. i don't want the user be able to use the app if he is not logged, so if he logout the auth page will show immediately.
2. every time the user data gets updated in the firebase db, i want the new data on my `user` variable in the `auth.ts` provider.

And you can use the `unsubscribe` method to cancel the `subscribe`.
